import React, { useState, useEffect } from 'react';
import { useNavigation } from '@react-navigation/native';
import { 
  ScrollView, 
  View, 
  Text, 
  StyleSheet, 
  TouchableOpacity, 
  TextInput,
  Alert,
  Modal,
  FlatList
} from 'react-native';

const AdminReports = () => {
  const navigation = useNavigation();
  
  const [reports, setReports] = useState([
    {
      id: "1",
      title: "Daily Revenue Report",
      type: "Financial",
      period: "2024-01-15",
      status: "Generated",
      generatedBy: "System",
      fileSize: "2.3 MB",
      downloadCount: 15,
      lastDownloaded: "2024-01-15T14:30:00Z"
    },
    {
      id: "2",
      title: "User Registration Analytics",
      type: "Analytics",
      period: "January 2024",
      status: "Generated",
      generatedBy: "Admin User",
      fileSize: "1.8 MB",
      downloadCount: 8,
      lastDownloaded: "2024-01-15T12:15:00Z"
    },
    {
      id: "3",
      title: "Hotel Booking Summary",
      type: "Booking",
      period: "Week 2, Jan 2024",
      status: "Generating",
      generatedBy: "System",
      fileSize: "0 MB",
      downloadCount: 0,
      lastDownloaded: null
    },
    {
      id: "4",
      title: "Emergency Response Report",
      type: "Emergency",
      period: "2024-01-01 to 2024-01-15",
      status: "Generated",
      generatedBy: "Emergency Team",
      fileSize: "3.1 MB",
      downloadCount: 3,
      lastDownloaded: "2024-01-15T10:45:00Z"
    },
    {
      id: "5",
      title: "Volunteer Performance Report",
      type: "Volunteer",
      period: "Q4 2023",
      status: "Generated",
      generatedBy: "HR Team",
      fileSize: "4.2 MB",
      downloadCount: 12,
      lastDownloaded: "2024-01-14T16:20:00Z"
    }
  ]);

  const [filteredReports, setFilteredReports] = useState(reports);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');
  const [showGenerateModal, setShowGenerateModal] = useState(false);

  useEffect(() => {
    filterReports();
  }, [searchTerm, filterType, filterStatus, reports]);

  const filterReports = () => {
    let filtered = reports;

    if (searchTerm) {
      filtered = filtered.filter(report =>
        report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        report.type.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    if (filterType !== 'all') {
      filtered = filtered.filter(report => report.type === filterType);
    }

    if (filterStatus !== 'all') {
      filtered = filtered.filter(report => report.status === filterStatus);
    }

    setFilteredReports(filtered);
  };

  const stats = {
    total: reports.length,
    generated: reports.filter(r => r.status === 'Generated').length,
    generating: reports.filter(r => r.status === 'Generating').length,
    totalDownloads: reports.reduce((sum, r) => sum + r.downloadCount, 0),
    totalSize: "11.4 MB"
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Generated': return '#388e3c';
      case 'Generating': return '#f57c00';
      case 'Failed': return '#d32f2f';
      default: return '#666';
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'Financial': return '💰';
      case 'Analytics': return '📊';
      case 'Booking': return '📅';
      case 'Emergency': return '🚨';
      case 'Volunteer': return '🤝';
      default: return '📄';
    }
  };

  const formatLastDownloaded = (lastDownloaded: string | null) => {
    if (!lastDownloaded) return 'Never';
    const date = new Date(lastDownloaded);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffHours < 24) return `${diffHours} hours ago`;
    if (diffDays < 7) return `${diffDays} days ago`;
    return date.toLocaleDateString();
  };

  const renderReportItem = ({ item: report }) => (
    <View style={styles.reportCard}>
      <View style={styles.reportHeader}>
        <View style={styles.reportInfo}>
          <Text style={styles.reportTitle}>
            {getTypeIcon(report.type)} {report.title}
          </Text>
          <Text style={styles.reportPeriod}>📅 Period: {report.period}</Text>
          <Text style={styles.reportGeneratedBy}>👤 Generated by: {report.generatedBy}</Text>
          <View style={styles.reportMeta}>
            <Text style={styles.reportSize}>📁 {report.fileSize}</Text>
            <Text style={styles.reportDownloads}>⬇️ {report.downloadCount} downloads</Text>
            <Text style={styles.reportLastDownload}>🕒 Last: {formatLastDownloaded(report.lastDownloaded)}</Text>
          </View>
        </View>
        <View style={styles.reportStatus}>
          <View style={[styles.statusBadge, { backgroundColor: getStatusColor(report.status) }]}>
            <Text style={styles.statusText}>{report.status}</Text>
          </View>
        </View>
      </View>
      
      <View style={styles.reportActions}>
        {report.status === 'Generated' && (
          <TouchableOpacity style={[styles.actionButton, styles.downloadButton]}>
            <Text style={styles.actionButtonText}>⬇️ Download</Text>
          </TouchableOpacity>
        )}
        <TouchableOpacity style={[styles.actionButton, styles.viewButton]}>
          <Text style={styles.actionButtonText}>👁️ Preview</Text>
        </TouchableOpacity>
        <TouchableOpacity style={[styles.actionButton, styles.shareButton]}>
          <Text style={styles.actionButtonText}>📤 Share</Text>
        </TouchableOpacity>
        {report.status === 'Generating' && (
          <TouchableOpacity style={[styles.actionButton, styles.cancelButton]}>
            <Text style={styles.actionButtonText}>❌ Cancel</Text>
          </TouchableOpacity>
        )}
      </View>
    </View>
  );

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.gridContainer}>
        {/* Reports Stats Cards */}
        <View style={styles.statsRow}>
          <View style={[styles.statCard, { backgroundColor: '#1976d2' }]}>
            <View style={styles.statContent}>
              <View>
                <Text style={styles.statNumber}>{stats.total}</Text>
                <Text style={styles.statLabel}>Total Reports</Text>
              </View>
              <Text style={styles.statIcon}>📊</Text>
            </View>
          </View>
          
          <View style={[styles.statCard, { backgroundColor: '#388e3c' }]}>
            <View style={styles.statContent}>
              <View>
                <Text style={styles.statNumber}>{stats.generated}</Text>
                <Text style={styles.statLabel}>Generated</Text>
              </View>
              <Text style={styles.statIcon}>✅</Text>
            </View>
          </View>
          
          <View style={[styles.statCard, { backgroundColor: '#f57c00' }]}>
            <View style={styles.statContent}>
              <View>
                <Text style={styles.statNumber}>{stats.generating}</Text>
                <Text style={styles.statLabel}>Generating</Text>
              </View>
              <Text style={styles.statIcon}>⏳</Text>
            </View>
          </View>
          
          <View style={[styles.statCard, { backgroundColor: '#7b1fa2' }]}>
            <View style={styles.statContent}>
              <View>
                <Text style={styles.statNumber}>{stats.totalDownloads}</Text>
                <Text style={styles.statLabel}>Downloads</Text>
              </View>
              <Text style={styles.statIcon}>⬇️</Text>
            </View>
          </View>
        </View>

        {/* Quick Stats */}
        <View style={styles.quickStats}>
          <View style={[styles.quickStatCard, { backgroundColor: '#4caf50' }]}>
            <View style={styles.quickStatContent}>
              <View>
                <Text style={styles.quickStatNumber}>{stats.totalSize}</Text>
                <Text style={styles.quickStatLabel}>Total Storage Used</Text>
              </View>
              <Text style={styles.quickStatIcon}>💾</Text>
            </View>
          </View>
          
          <View style={[styles.quickStatCard, { backgroundColor: '#ff9800' }]}>
            <View style={styles.quickStatContent}>
              <View>
                <Text style={styles.quickStatNumber}>5</Text>
                <Text style={styles.quickStatLabel}>Report Types</Text>
              </View>
              <Text style={styles.quickStatIcon}>📋</Text>
            </View>
          </View>
        </View>

        {/* Reports Management Paper */}
        <View style={styles.managementPaper}>
          <View style={styles.managementHeader}>
            <Text style={styles.managementTitle}>
              Analytics & Reports
            </Text>
            <TouchableOpacity
              style={styles.addButton}
              onPress={() => setShowGenerateModal(true)}
            >
              <Text style={styles.addButtonText}>📊 Generate Report</Text>
            </TouchableOpacity>
          </View>

          {/* Filters */}
          <View style={styles.filtersContainer}>
            <TextInput
              style={styles.searchInput}
              placeholder="Search reports..."
              value={searchTerm}
              onChangeText={setSearchTerm}
            />
            
            <View style={styles.filterRow}>
              <TouchableOpacity 
                style={[styles.filterButton, filterType === 'all' && styles.activeFilter]}
                onPress={() => setFilterType('all')}
              >
                <Text style={[styles.filterText, filterType === 'all' && styles.activeFilterText]}>All Types</Text>
              </TouchableOpacity>
              <TouchableOpacity 
                style={[styles.filterButton, filterType === 'Financial' && styles.activeFilter]}
                onPress={() => setFilterType('Financial')}
              >
                <Text style={[styles.filterText, filterType === 'Financial' && styles.activeFilterText]}>💰 Financial</Text>
              </TouchableOpacity>
              <TouchableOpacity 
                style={[styles.filterButton, filterType === 'Analytics' && styles.activeFilter]}
                onPress={() => setFilterType('Analytics')}
              >
                <Text style={[styles.filterText, filterType === 'Analytics' && styles.activeFilterText]}>📊 Analytics</Text>
              </TouchableOpacity>
              <TouchableOpacity 
                style={[styles.filterButton, filterType === 'Booking' && styles.activeFilter]}
                onPress={() => setFilterType('Booking')}
              >
                <Text style={[styles.filterText, filterType === 'Booking' && styles.activeFilterText]}>📅 Booking</Text>
              </TouchableOpacity>
            </View>

            <View style={styles.filterRow}>
              <TouchableOpacity 
                style={[styles.filterButton, filterStatus === 'all' && styles.activeFilter]}
                onPress={() => setFilterStatus('all')}
              >
                <Text style={[styles.filterText, filterStatus === 'all' && styles.activeFilterText]}>All Status</Text>
              </TouchableOpacity>
              <TouchableOpacity 
                style={[styles.filterButton, filterStatus === 'Generated' && styles.activeFilter]}
                onPress={() => setFilterStatus('Generated')}
              >
                <Text style={[styles.filterText, filterStatus === 'Generated' && styles.activeFilterText]}>✅ Generated</Text>
              </TouchableOpacity>
              <TouchableOpacity 
                style={[styles.filterButton, filterStatus === 'Generating' && styles.activeFilter]}
                onPress={() => setFilterStatus('Generating')}
              >
                <Text style={[styles.filterText, filterStatus === 'Generating' && styles.activeFilterText]}>⏳ Generating</Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Reports List */}
          <FlatList
            data={filteredReports}
            renderItem={renderReportItem}
            keyExtractor={(item) => item.id}
            scrollEnabled={false}
            style={styles.reportsList}
          />

          {filteredReports.length === 0 && (
            <View style={styles.emptyState}>
              <Text style={styles.emptyIcon}>📊</Text>
              <Text style={styles.emptyTitle}>No reports found</Text>
              <Text style={styles.emptySubtitle}>
                {searchTerm || filterType !== 'all' || filterStatus !== 'all'
                  ? 'Try adjusting your search or filter criteria'
                  : 'Generate your first report to get started'}
              </Text>
            </View>
          )}
        </View>
      </View>

      <TouchableOpacity 
        style={styles.backButton} 
        onPress={() => navigation.goBack()}
      >
        <Text style={styles.backButtonText}>← Back to Admin Menu</Text>
      </TouchableOpacity>
    </ScrollView>
  );
};

export default AdminReports;

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingTop: 32,
    paddingBottom: 32,
    paddingHorizontal: 20,
    backgroundColor: '#f5f5f5',
  },
  
  gridContainer: {
    gap: 24,
  },
  
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  
  statCard: {
    flex: 1,
    minWidth: 150,
    borderRadius: 4,
    padding: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  
  statContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  
  statNumber: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
  },
  
  statLabel: {
    fontSize: 14,
    color: 'white',
    opacity: 0.9,
  },
  
  statIcon: {
    fontSize: 40,
    opacity: 0.8,
  },
  
  quickStats: {
    flexDirection: 'row',
    gap: 16,
  },
  
  quickStatCard: {
    flex: 1,
    borderRadius: 4,
    padding: 20,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  
  quickStatContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  
  quickStatNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
  },
  
  quickStatLabel: {
    fontSize: 14,
    color: 'white',
    opacity: 0.9,
  },
  
  quickStatIcon: {
    fontSize: 32,
    opacity: 0.8,
  },
  
  managementPaper: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    padding: 24,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  
  managementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  
  managementTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1976d2',
  },
  
  addButton: {
    backgroundColor: '#1976d2',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 4,
  },
  
  addButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  
  filtersContainer: {
    marginBottom: 24,
    gap: 16,
  },
  
  searchInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 4,
    padding: 12,
    backgroundColor: 'white',
    fontSize: 16,
  },
  
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    backgroundColor: 'white',
  },
  
  activeFilter: {
    backgroundColor: '#1976d2',
    borderColor: '#1976d2',
  },
  
  filterText: {
    fontSize: 14,
    color: '#666',
  },
  
  activeFilterText: {
    color: 'white',
  },
  
  reportsList: {
    gap: 16,
  },
  
  reportCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  
  reportInfo: {
    flex: 1,
  },
  
  reportTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  
  reportPeriod: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  
  reportGeneratedBy: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  
  reportMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  
  reportSize: {
    fontSize: 12,
    color: '#666',
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  
  reportDownloads: {
    fontSize: 12,
    color: '#666',
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  
  reportLastDownload: {
    fontSize: 12,
    color: '#666',
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  
  reportStatus: {
    alignItems: 'flex-end',
  },
  
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  
  statusText: {
    fontSize: 12,
    color: 'white',
    fontWeight: 'bold',
  },
  
  reportActions: {
    flexDirection: 'row',
    gap: 8,
  },
  
  actionButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 4,
    alignItems: 'center',
  },
  
  downloadButton: {
    backgroundColor: '#388e3c',
  },
  
  viewButton: {
    backgroundColor: '#1976d2',
  },
  
  shareButton: {
    backgroundColor: '#f57c00',
  },
  
  cancelButton: {
    backgroundColor: '#d32f2f',
  },
  
  actionButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  
  emptyState: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  
  emptyIcon: {
    fontSize: 80,
    color: '#ccc',
    marginBottom: 16,
  },
  
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#666',
    marginBottom: 8,
  },
  
  emptySubtitle: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
  },
  
  backButton: {
    backgroundColor: '#666',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  backButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
});
